version: "3.9"
services:
  webapp:
    build:
      context: ./
      dockerfile: Dockerfile.web
    image: flutter-web
    volumes: 
      - "/Users/palakotisatishchandra/Desktop/flutter-setup/podcast:/root/podcast"
    ports:
     - "4040:4040"
   

  # android:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.android
  #   image: flutter-android
  # ios:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.ios
  #   image: flutter-ios
      